# Required
[[plugins]]
repo = 'Shougo/dein.vim'

# vim内でのgitの操作
[[plugins]]
repo = 'tpope/vim-fugitive'

# javascript syntax and indent plugins
[[plugins]]
repo = 'billyvg/tigris.nvim'
on_ft = ['javascript', 'javascript.jsx']
hook_post_update = '''
  let g:dein#plugin.build = './install.sh'
'''

[[plugins]]
repo = 'othree/html5.vim'
on_ft = ['html', 'ejs']

# ソースコード上のメソッド宣言、変数宣言の一覧を表示
[[plugins]]
repo = 'vim-scripts/taglist.vim'

# テキストを括弧とかで囲むやつ
[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'tpope/vim-repeat'

# emmet
[[plugins]]
repo = 'mattn/emmet-vim'

# コメント処理
[[plugins]]
repo = 'scrooloose/nerdcommenter.git'

# .editorconfig
[[plugins]]
repo = 'editorconfig/editorconfig-vim'

# unite.vim
[[plugins]]
repo = 'Shougo/unite.vim'

# vimfiler
[[plugins]]
repo = 'Shougo/vimfiler'

# unite/yank
[[plugins]]
repo = 'Shougo/neoyank.vim'

## vim内でshellを使える
[[plugins]]
repo = 'Shougo/vimshell'

[[plugins]]
repo = 'w0ng/vim-hybrid'

[[plugins]]
repo = 'dracula/vim'
